### ISSUE TITLE
Sprint Focus: Jupyter Notebooks week 5 of 6

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-notebook#94]
## Goals for the Sprint
* [x] #40 - PDF rendering from nbpresent slideshows - finish up CLI portion and write tests
    * ISR tested this and it isn't ready for prime time yet.
* [x] #34 - turn syncer into stand-alone extension and conda package
* [x] #57 Working conda recipies for all 4-5 extensions
* [x] #82 - NBSetup tools completed
* [x] #18 - prototype jupyter extension (needs to incorporate nbSetup)
* [x] #95 3 (5?) extensions refactored to use NBSetup tools
* [x] #85 Refactor repos into individual repositories
* [x] #47 Define/spec for integration with anaconda server (anaconda notebook upload to A-Cloud)
* [x] Casper.JS headless browser test of nbpresent working (future: integrate into nbSetup)
* [x] Marketing discussions - how do we promote the work for the epic (idea: series of 3 blog posts, 1 hr webinar: anaconda, notebooks, nbpresent and notebook presentations, extensions, how to build your own)

## Stretch Goals
* [ ] ~~#50 Implement integration with Anaconda Server  (anaconda notebook upload to A-Cloud)~~
    * I think this is just supposed to be #47, already listed above, because this is `anaconda info` (which doesn't exist yet, TTBOMK) -- basically a way to view the status of 'your stuff' on Anaconda Enterprise.
* [x] #89 Build with Anaconda Build System

Clean-up
- cross platform
- installable from the channel
- automated tests

Deferred to next sprint:
- docs
- cross-platform testing
- polishing and loose ends
